---
- name: Copy Updates (E-0/6)
  hosts: vnc_client

  tasks:

  - name: copy xtartup file file (E-1/12)
    become: true
    command: cp /home/{{ new_username }}/{{ dir_project }}/vnc_client/ansible/xstartup /home/{{ new_username }}/.vnc/xstartup

  - name: chmod tws-latest-linux-x86.sh
    command: chmod u+x tws-latest-linux-x86.sh
    args:
      chdir: /home/{{ new_username }}/{{ dir_project }}/vnc_client/tws/

  - name: install tws-latest-linux-x86.sh
    command: ./tws-latest-linux-x86.sh
    args:
      chdir: /home/{{ new_username }}/{{ dir_project }}/vnc_client/tws/

  - name: chmod ibgateway-stable-standalone-linux-x64.sh
    command: chmod u+x ibgateway-stable-standalone-linux-x64.sh
    args:
      chdir: /home/{{ new_username }}/{{ dir_project }}/vnc_client/tws/

  - name: install ibgateway-stable-standalone-linux-x64.sh
    command: ./ibgateway-stable-standalone-linux-x64.sh
    args:
      chdir: /home/{{ new_username }}/{{ dir_project }}/vnc_client/tws/
