---
- name: Setup vncserver (E-0/6)
  hosts: vnc_client

  tasks:

    - name: create .vnc directory and insert password (E-1/6)
      expect:
        command: vncserver
        echo: yes
        responses:
          'Password:': 'password'
          'Verify': 'password'
          'Would you like to enter a view-only password (y/n)?': 'n'

    - name: kill current vncserver process (E-2/6)
      become: true
      shell: "killall Xtightvnc"

    - name: backup xstartup file (E-3/6)
      become: true
      command: mv /home/{{ new_username }}/.vnc/xstartup /home/{{ new_username }}/.vnc/xstartup.bak

    - name: copy xstartup file from git server (E-4/6)
      become: true
      command: cp /home/{{ new_username }}/{{ dir_project }}/vncserver/xstartup /home/{{ new_username }}/.vnc/xstartup

    - name: chmod xstartup (E-5/6)
      become: true
      shell: chmod u=rwx,g=rwx,o=rx /home/{{ new_username }}/.vnc/xstartup

    - name: re-start vncserver process (E-6/6)
      become: true
      command: vncserver
